### ISSUE TITLE
What is the purpose of ModelSerializer?

### ISSUE THREAD

**Issue by netsensei** [cleentfaar/slack#16]
Hi Cas,

I noticed that the `CL\Slack\Serializer\ModelSerializer` class is never integrated in the library. It exists, but none of the other parts are calling it. Except for the `AbstractModelTest` class which uses it to test the getters of the models.

I was wondering if you plan to use it in the library or if it's merely there for testing purposes.

Thx!

Matthias

**Comment by cleentfaar** [comment]
Hi Matthias,

I havent been active on personal projects last few months; I think this is a loose end which I didnt finish properly at the time.

I will look into it the coming week, thanks for reporting!

**Comment by cleentfaar** [comment]
@netsensei Removed the modelserializer for now, might come back later if I find proper use for it again. Thanks for reporting!
