### ISSUE TITLE
Failed to send payload with guzzlehttp/guzzle >6.0.0

### ISSUE THREAD

**Issue by AndrzejFR** [cleentfaar/slack#23]
After running compose update guzzlehttp/guzzle package got updated to 6.0.1 and effectively broke sending messages. I fixed it by fixing it at version 5.3.0 in my composer.json.

I don't know what has changed in guzzle package but you have to restrict it to version below 6.0.0 or make it compatible with new version.

**Comment by Zxurian** [comment]
it looks like more than just that broke. Even downgrading to 5.3.0 doesn't send attachments anymore.

**Comment by Zxurian** [comment]
so I was able to get GuzzleHttp 6 working as well as attachments with a simple hack, although it will probably need further refinement for production.

in `CL/Slack/Transport/ApiClient.php` make the following changes
```php
    private function createRequest($method, array $payload)
    {
    	$payload['attachments'] = json_encode($payload['attachments']);
    	
    	$request = $this->client->createRequest('POST', self::API_BASE_URL.$method, [], $payload);

        return $request;
    }
```

**Comment by yaK2manD** [comment]
I tried this one but it failed.
Any news on this issue?

**Comment by cleentfaar** [comment]
@Zxurian @yaK2manD I'm sorry about the late reply, I have merged a PR that should fix this moments ago: https://github.com/cleentfaar/slack/pull/14

I haven't released a new version yet (still catching up on all the issues) but you can use the master version to try it out.

**Comment by cleentfaar** [comment]
I don't think that fixes the guzzle issue by the way, I'm working on a fix asap

**Comment by cleentfaar** [comment]
Guzzle has been upgraded to v6 in the latest release (0.17.1) so I think this issue can be closed. Let me know if it didn't fix your problem and I will reopen this issue.
