### ISSUE TITLE
Lack of payload for groups.info

### ISSUE THREAD

**Issue by dinhhoanglong91** [cleentfaar/slack#26]
There is api named `groups.info` but has been implemented yet.
https://api.slack.com/methods/groups.info

Could you implement this :bow:

**Comment by dinhhoanglong91** [comment]
ping @cleentfaar

**Comment by cleentfaar** [comment]
@dinhhoanglong91 Sorry for the late reply, I'm happy to implement this of course, I'm just catching up on other issues first now so probably will get to it somewhere in the next few days.

**Comment by cleentfaar** [comment]
FYI @raupie has been nice enough to create a PR that fixes this and other issues: https://github.com/cleentfaar/slack/pull/32/

I will try to get it merged soon

**Comment by cleentfaar** [comment]
https://github.com/cleentfaar/slack/pull/42 will fix this

**Comment by cleentfaar** [comment]
#42 Has been merged so this should have been resolved, if not please reopen
