### ISSUE TITLE
IM Channels returning Null

### ISSUE THREAD

**Issue by raupie** [cleentfaar/slack#34]
Attempting to get an authenticated users ImChannels via the ImListPayload class. The getImChannels() response returns null.

**Comment by cleentfaar** [comment]
@raupie Thanks for reporting this and sorry for the late reply. I will be looking into this asap.

**Comment by cleentfaar** [comment]
Appearantly you already made a PR for this :smile:: https://github.com/cleentfaar/slack/pull/32, thanks for that! I'm just waiting for you to do a few more fixes so I can merge it.
