### ISSUE TITLE
Exception thrown when trying to send message

### ISSUE THREAD

**Issue by chrisemerson** [cleentfaar/slack#4]
Fatal error: Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@JMS\Serializer\Annotation\Type" in property CL\Slack\Payload\ChatPostMessagePayload::$channel does not exist, or could not be auto-loaded.' in [...path...]/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
    Stack trace:
    #0 [...path...]/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
    #1 [...path...]/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation()
    #2 [...path...]/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations()
    #3 [...path...]/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.p in [...path...]/vendor/cleentfaar/slack/CL/Slack/Transport/ApiClient.php on line 108

I have confirmed that the Type.php file is there in the right location and the right namespace, and composer can load it through its autoloader - however the Doctrine Annotations library bypasses the standard PHP autoloading mechanism for some reason, and you have to register annotations with the AnnotationRegistry. I'm sure the JMSSerializer library must have done this, and 'use'ing the namespace and aliasing it as you are doing in ChatPostMessagePayload is supposed to fix this (`use JMS\Serializer\Annotation as Serializer`), so I'm unsure why this is happening myself. I'm not very familiar with the JMS Serializer library though.

**Comment by cleentfaar** [comment]
@chrisemerson Sorry, your messages seem to have gone past me! 

If you haven't solved your issue already, please try updating to the latest version (0.12). Many things have been improved. I'm really looking for feedback on my code so even if you are not using this package anymore, I'd like to hear what you had difficulties with.

I'm also curious about you seeming to need to extend the `ApiClient` itself, can I make some modification that would suit your scenario better?

**Comment by cleentfaar** [comment]
FYI: seeing as you have commented on this after the latest release, I'm assuming you were using the latest version and will try to debug/fix what is going on asap.

**Comment by cleentfaar** [comment]
Seeing as you have commented on this after the latest release, I'm assuming you were using the latest version and just now noticed that I didn't push my latest fix yet; a missing dependency for composer. I have done so now and created a new release (0.12.2), please try it out and let me know if the issue still occurs.

**Comment by cleentfaar** [comment]
Closing, please let me know if the issue still occurs with the latest release

**Comment by deancsmith** [comment]
Hi @cleentfaar, I was also just getting this error - I'm adding your library to a small Silex CLI app.

Adding:

```php
\Doctrine\Common\Annotations\AnnotationRegistry::registerLoader('class_exists');
```

To my app.php (basically my bootstrap, similarly to what you have here: https://github.com/cleentfaar/slack/blob/master/src/CL/Slack/Tests/bootstrap.php) solved my problem.

**Comment by cleentfaar** [comment]
Hey @deancsmith 

I just made a fix to the  `PayloadSerializer` that automatically registers the annotation loader you mentioned. I'm curious if this will fix the issue for people with the same problem. Would you mind updating the package and check if it works even without registering the loader yourself?

If it works I will create a new release `0.13.2` and update relevant docs.

FYI: in the future I aim to completely get rid of the annotation dependency by using a `.yml` file for the mapping.

**Comment by deancsmith** [comment]
I updated to dev-master (9b10c43) and commented out the registerLoader line et voila it is working perfectly.

I think it's better (for users) the way you have it now so maybe update your docs. and push 0.13.2.

**Comment by cleentfaar** [comment]
New release has been created (`0.13.2`). 

Thanks again for helping me debug this issue!

**Comment by chrisemerson** [comment]
Thanks - sorry for the lack of response, haven't had much of a chance to look at this issue again recently. I'll give it a go with the new version and see how I get on.
