### ISSUE TITLE
Update documentation in line with 013.x

### ISSUE THREAD

**Issue by deancsmith** [cleentfaar/slack#7]
Firstly, your library looks great and I am looking forward to using it.

Could you possibly update your usage documentation in line with your latest changes?

I've tried to get up and running but am getting stuck with:

```
Catchable fatal error: Argument 2 passed to CL\Slack\Transport\ApiClient::__construct() must be an instance of CL\Slack\Util\PayloadSerializer, none given, called in C:\inetpub\wwwroot\src\SD\SOS\Console\Check.php on line 19 and defined in C:\inetpub\wwwroot\vendor\cleentfaar\slack\src\CL\Slack\Transport\ApiClient.php on line 78
```
I can see that you've added a PayloadSerializer param to ApiClient but can't seem to pass it the right thing.

e.g. I've tried:

```php
$payloadSerialiazer = new \CL\Slack\Util\PayloadSerializer();
$client = new \CL\Slack\Transport\ApiClient($apiToken, $payloadSerializer);
```

But no luck.

You also give the example of $payload->setMessage(), but this is depreciated in favour of $payload->setText()?

**Comment by cleentfaar** [comment]
Hey @deancsmith,

thanks for using my library! I'm not sure why you are getting this error. I did a lot of fixes last night so you might want to try updating the package to see if it's resolved. To make sure it works for others, I have just created a working example using the following code:

```php
<?php
$apiClient = new ApiClient('your-token-here', new PayloadSerializer());

$message = new ChatPostMessagePayload();
$message->setChannel('#general');
$message->setText('Hello world!');

$response = $apiClient->send($message);

if (!$response->isOk()) {
    throw new \Exception(sprintf('Failed to send Slack message: %s', $response->getErrorExplanation()));
}
```

Which gives me the following in Slack:
![screen shot 2015-02-08 at 14 13 13](https://cloud.githubusercontent.com/assets/795661/6096633/abf0289a-af9c-11e4-93c9-65c070d8d672.png)


Could you try copy that code and update the token, and let me know if that works? If it doesn't can you supply a bit more code / logging so I can debug better? Thanks!

**Comment by deancsmith** [comment]
Thanks for the fast response, that seems to work, I think once I did that I was encountering the Annotations metadata loading issue I just posted about in issue #4.

Could you just update the constructor in ApiClient to the below to make supplying the serializer optional? I can do as a PR.

```php
    /**
     * @param string|null                   $token
     * @param PayloadSerializer             $serializer
     * @param ClientInterface|null          $client
     * @param EventDispatcherInterface|null $eventDispatcher
     */
    public function __construct(
        $token = null,
        PayloadSerializer $serializer = null,
        ClientInterface $client = null,
        EventDispatcherInterface $eventDispatcher = null
    ) {
        $this->token           = $token;
        $this->serializer      = $serializer ?: new PayloadSerializer();
        $this->client          = $client ?: new Client();
        $this->eventDispatcher = $eventDispatcher ?: new EventDispatcher();
    }
```

**Comment by deancsmith** [comment]
Fixed the cURL issue and it's working fine now, thanks!

**Comment by cleentfaar** [comment]
Ah good to hear! Feedback is very welcome as these packages are my first real attempt at making community software.

Seeing curl was the issue in your case, would it be a good idea to add a `ext-curl` dependency to the composer.json of this bundle? Or was it more of a configuration/firewall issue for you?

As a side-note: I'm not sure why you wanted me to make this argument nullable: it is required for the payload to be serialized and sent to the Slack API. If you need it to be nullable to test something; couldn't you just do that in your downloaded `cleentfaar/slack` package, and then remove it again once it's fixed?

**Comment by deancsmith** [comment]
It's a very good and useful first attempt!

My issue was just a general Guzzle issue on Windows, the bundled CA certs are out of date so you need to either turn off peer verification in cURL OPTS or pass through a working bundle.

```php
$client = new \GuzzleHttp\Client();
$client->setDefaultOption('verify', 'C:\Program Files (x86)\Git\bin\curl-ca-bundle.crt');

$clientApi =  new ApiClient($app['slack.api_token'], new PayloadSerializer(), $client);
```

In my above code I allowed it to be nullable but then set it to PayloadSerializer() by default if null was passed through. My question is why bother forcing people to set it when the default is (maybe?) acceptable. I might be missing something here? (have only glanced at your package structure, I like what I see though, especially the way you have used annotations!)

```php
$this->serializer      = $serializer ?: new PayloadSerializer();
```

**Comment by cleentfaar** [comment]
Hm, interesting point, it does seem unnecessary to have that required...

Fixed with latest commit, (it's optional again). Sorry for the fuss :smile:!

Would you be interested in writing a small piece of documentation for Windows users having these certificate problems? I think the bottom of the README.md could have a FAQ section with your issue in it, and the code above as a solution (answer). 

If you can get a PR ready I'm happy to merge it.

**Comment by deancsmith** [comment]
All good! Thanks again.

And will do a documentation PR! (not right now, it's almost 2am my time)
